export const navData = [
  "Avatar",
  "Badge",
  "Breadcrumb",
  "Buttons",
  "Calendar",
  "Cards",
  "Checkbox",
  "Chips",
  "Date pickers",
  "Dividers",
  "Dropdowns",
  "Help text",
  "Icon",
  "Inline editable fields",
  "Inputs",
  "Link",
  "Messages",
  "Meta list",
  "Modals",
  "Navigation - Horizontal",
  "Navigation - Vertical",
  "Page headers",
  "Pagination",
  "Pill",
  "Popover",
  "Progress indicators",
  "Radio",
  "Rich text editor",
  "Sidesheet",
  "Sliders",
  "Status hint",
  "Stepper",
  "Switch",
  "Tables",
  "Tabs",
  "Time picker",
  "Toast",
  "Tooltip",
];

export default navData;